# Generated by Django 3.2.7 on 2021-09-24 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210924_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(default='', help_text='Provide a URL-link to Image'),
        ),
    ]
